spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "wwe brock"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    name: app.log
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwtSecret: secret
  jwtExpirationInMs: 3600000

cors:
  allowedOrings: '*'
